pyca/bcrypt

.gitignore, README.rst
=> Update readme and ignores

README.rst, src/bcrypt/__init__.py, tests/test_bcrypt.py
Continues #36
Closes #36
Fixes #25
=> Continue #36

src/_csrc/bcrypt_pbkdf.c, src/build_bcrypt.py
This is dependent on #68 and can't be reviewed until after that merges.
=> Add bcrypt pbkdf bindings

README.rst, src/bcrypt/__init__.py, src/build_bcrypt.py, tests/test_bcrypt.py
fixes #74 
This also removes a lot of duplication in test vectors.
=> Add checkpw

.travis.yml, MANIFEST.in, tox.ini
=> Fix packaging

Jenkinsfile
=> Remove unnsecary stuff from Jenkinsfile

.jenkins/Jenkinsfile-wheel-builder, .travis.yml, Jenkinsfile, README.rst, setup.py, tasks.py, tox.ini
Resolves #132.
I also removed the build branch restriction in .travis.yml so I could test my feature branch before submitting this PR. Let me know if you want that left out.
=> Drop Python 2.6 and 3.3 support

README.rst
=> update the readme to note alternatives but still say bcrypt is good

.jenkins/Jenkinsfile-wheel-builder
=> switch wheel building back to using pip wheel

.travis.yml
`travis encrypt` is not great software
=> try encrypting this again

README.rst
Hi, I just added two lines for some dependencies for alpine.
=> Updated README.md with alpine dependecies

.azure-pipelines/wheel-builder.yml, .github/workflows/ci.yml, .travis.yml, README.rst, azure-pipelines.yml, setup.py, tox.ini
Also drops Python 3.4 support.
=> Move Windows CI to Github Actions

.github/workflows/wheel-builder.yml
Added ARM64 Support to Github Actions for wheel development.
Resolves the second step for #206. 
@reaperhulk Please review and let me know if any changes required.
=> ARM64 Support to Github Actions for wheel development

.github/workflows/wheel-builder.yml
=> all inside a single string

README.rst, src/bcrypt/__about__.py
The legacy killing release (well, mostly).
=> bump for 3.2.0

.circleci/build-wheel.sh, .circleci/config.yml, MANIFEST.in
Follow up PR will kill the emulated aarch64 code in actions.
=> circleci support for linux arm64

.github/workflows/ci.yml, MANIFEST.in
add caching, pin rs toolchain hash, update some versions
=> CI updates

src/_bcrypt/src/lib.rs, src/bcrypt/__init__.py
They aren't required now that we no longer use the OpenBSD library
=> Remove regexp shenanigans

src/bcrypt/__init__.py, tests/reference/Makefile, tests/reference/bcrypt_reference.go, tests/reference/go.mod, tests/reference/go.sum, tests/test_bcrypt.py, tox.ini
Just wanted to make sure you have an up-to-date version of the patch :-)
=> allow null bytes in inputs

.github/workflows/wheel-builder.yml
we no longer have manylinux2010
=> bump wheel builder actions/checkout version

.circleci/config.yml, .github/workflows/wheel-builder.yml
https://github.com/pypa/manylinux/pull/1437
=> remove manylinux 2.24

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/wheel-builder.yml, README.rst, pyproject.toml, setup.cfg, setup.py
=> drop py36, pypy-3.7, test py311, other housecleaning

.github/workflows/ci.yml
This is an incarnation of https://github.com/pyca/pyopenssl/pull/1146
and https://github.com/pyca/cryptography/pull/7643.
https://github.com/marketplace/actions/alls-green#why
=> Add a gate/check job to the GHA CI workflow

.github/workflows/pypi-publish.yml, .github/workflows/wheel-builder.yml, release.py
=> Import improvements from cryptography wheel building and release

.github/workflows/ci.yml, .github/workflows/pypi-publish.yml, pyproject.toml
=> Update CI for 3.13

.github/workflows/ci.yml
=> use 3.14.0 in CI
