README.rst

This was helpfully pointed out in https://github.com/pyca/bcrypt/issues/41 by @jbolda.
The only package I needed was ```libffi-dev```, so maybe someone can confirm the full list.  I also fixed your PyPi badge.

Update README to include additional install steps

---

README.rst
setup.py

This resolves the recent comment on #49 that noted we still hadn't put in warnings like we promised to.

raise a decent error if pypy <2.6 + update README

---

src/crypt_blowfish-1.3/crypt_blowfish.c
src/crypt_blowfish-1.3/crypt_blowfish.h
src/crypt_blowfish-1.3/crypt_gensalt.c
src/crypt_blowfish-1.3/crypt_gensalt.h
src/crypt_blowfish-1.3/wrapper.c

I have added bcrypt_ prefix for all public symbols (excluding crypt* functions from wrapper which are used by CFFI only).
Looks like now it works under Apache and does not interfere with APR's functions.
Actual sym list:
```
$ nm -D build/lib.linux-x86_64-2.7/bcrypt/_bcrypt.so
0000000000003430 T bcrypt_crypt_blowfish_rn
0000000000003750 T bcrypt_crypt_gensalt_blowfish_rn
0000000000003950 T bcrypt_crypt_gensalt_extended_rn
0000000000003ab0 T bcrypt_crypt_gensalt_md5_rn
0000000000003890 T bcrypt_crypt_gensalt_traditional_rn
0000000000206160 D bcrypt_crypt_itoa64
00000000000033f0 T bcrypt_crypt_output_magic
00000000002061a1 B __bss_start
0000000000003d20 T crypt
0000000000003f20 T crypt_gensalt
0000000000003ed0 T crypt_gensalt_ra
0000000000003d80 T crypt_gensalt_rn
0000000000003cd0 T crypt_r …
```

Add vendor prefixes for public sym names

---

tests/test_bcrypt.py

This PR pulls some test vectors that get used in multiple places into a single location. The diff is, unfortunately, confusing.

refactor tests to stop duplicating vectors

---

tasks.py

This will tag the release in github, upload the sdist, purge the PyPI cache, trigger the wheel builder, and download/upload the wheels.

invoke task to make bcrypt releases a bit simpler

---

src/bcrypt/__init__.py
tests/test_bcrypt.py

restore compatibility with 2.0.0's fix for wraparound bug

---

src/_csrc/portable_endian.h
src/_csrc/pycabcrypt.h
src/_csrc/sha2.h

Fixes compilation on alpine linux and cleans up a bunch of warnings that can occur on platforms that don't use glibc.

Fix alpine

---

README.rst
src/bcrypt/__init__.py
tests/test_bcrypt.py

Currently using bcrypt 3.0 with passlib is a bit broken, because it it inputs a precomputed ``$2y$`` salt and expects to get back out a ``$2y$`` hash (and it verifies that it does that), however instead it's getting back a ``$2b$`` hash. Giving a ``$2b$`` output when you give it a ``$2y$`` input also means it breaks the most logical way to verify a bcrypt'd password since:
```python
import bcrypt
assert bcrypt.hashpw(plaintext, hashed_with_2y) == hashed_with_2y
```
would fail because instead of a ``$2y$`` we'd return a ``$2b$``.
So this change will ensure that ``hashpw()`` returns the same prefix it was given originally. We still don't support the ``$2y$`` prefix when passed into ``gensalt()``, so getting a ``$2y$`` out of ``hashpw()`` will still require either pre-existing data or …

Inputing a 2y salt should output a 2y hash

---

README.rst

Use checkpw() instead of ==

---

src/bcrypt/__init__.py

These functions take `char *` which means passing `unsigned char[]` isn't right. cffi 1.8.3 includes some new code that detects this and complains.

we should use the right type for our buffers. fixes a cffi warning

---

src/bcrypt/__init__.py
tests/test_bcrypt.py

Previously it would silently accept extra data, and overread a buffer on truncated data.
Reported by Matthew Russell

Correctly handle invalid hashed passwords in bcrypt.checkpw.

---

src/_csrc/portable_endian.h

There seems to be one opening parenthesis too many here on both lines.
Discovered after running into the following errors while cross-compiling for PowerPC/Qoriq:
```
src/_csrc/sha2.c: In function 'SHA256Final':
src/_csrc/sha2.c:484: error: expected ')' before ';' token
src/_csrc/sha2.c:485: error: expected ')' before '}' token
src/_csrc/sha2.c:485: error: expected ';' before '}' token
```

Fix compile issue for PowerPC

---

MANIFEST.in
wheel-scripts/build_wheels.sh
wheel-scripts/docker.sh

These scripts will store the manylinux1 wheels in a dir called `wheelhouse` in your current working directory. Note that at the moment these scripts _will not work_ unless you already have that dir and it contains `cffi` manylinux1 wheels (as libffi is not present in the docker container).
This probably shouldn't be merged until it has some documentation on how to use it.

add build scripts for creating manylinux1 wheels

---

src/bcrypt/__init__.py
tests/test_bcrypt.py

Pull request as suggested for #103

Warn upon too few bcrypt.kdf() rounds

---

src/_csrc/portable_endian.h
src/_csrc/pycabcrypt.h

Solaris has all the needed byte-order twiddling macros built-in, but it uses different names.  Same with some of the types.  All tests pass on SPARC and x86, 32 and 64 bit.

Define types and byte-order macros for Solaris.

---

Jenkinsfile
MANIFEST.in

This is WIP until FreeBSD 11 is added (and it actually works)

Switch to Jenkinsfile for jenkins job configuration

---

src/_csrc/bcrypt_pbkdf.c
src/_csrc/blf.h
src/_csrc/pycabcrypt.h

Can't compil on msys/mingw64
Error message:
build/temp.mingw-2.7/src/_csrc/bcrypt_pbkdf.o:bcrypt_pbkdf.c:(.text+0x0): multiple definition of `_abs64'
build/temp.mingw-2.7/src/_csrc/bcrypt.o:bcrypt.c:(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
Corrections:
In "src/_csrc/bcrypt_pbkdf.c", re-organize:
#include <sys/types.h>
#include <stdlib.h>
#include <string.h>
#include "pycabcrypt.h"
#include "blf.h"
#include "sha2.h"
In "src/_csrc/blf.h", move #include "pycabcrypt.h":
#ifndef BLF_H
#define BLF_H
#include "pycabcrypt.h"
...
#endif
In "src/_csrc/pycabcrypt.h", add :
#ifndef PYCABCRYPT
#define PYCABCRYPT
...
#endif

Fixes link editing errors in msys / mingw64

---

setup.py

The trove classifiers are displayed on PyPI and so helps inform library users about the project. Document that the project is stable and ready for use in production. Document the project is licensed under the Apache software license.

Add useful trove classifiers (dev status & license)

---

src/bcrypt/__init__.py

Use an application relative import when importing _bcrypt.  This allows the package to work even in odd locations, such as `pip install --target . bcrypt` (rather than in the site-packages or user packages directory).

Use a relative import.

---

.travis.yml
Jenkinsfile
tox.ini

This PR:
* Updates mac image
* Will build tags on travis now
* Notifies the IRC channel for builds (so we don't miss failures like we did just now)
* Ignores flake8's W504
* Removes freebsd from our Jenkinsfile since that builder no longer exists.

fix our CI rot

---

.jenkins/Jenkinsfile-wheel-builder

https://github.com/pyca/infra/blob/0db7401a572ba0e4d32bd47695922b29d256dce7/external-projects/Jenkinsfile-cffi-wheel-builder#L99-L131

port the cffi libffi build code

---

src/_csrc/portable_endian.h

This allows the bcrypt module to be built under Haiku (https://www.haiku-os.org) and its Python3 installation. Build completes and all tests pass:
```
======================================================= test session starts ========================================================
platform haiku1 -- Python 3.6.7, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: /boot/home/git/bcrypt, inifile:
collected 145 items                                                                                                                
tests/test_bcrypt.py ....................................................................................................... [ 71%]
..........................................                                                                                   [100%] …
```

Added portable_endian support for Haiku OS

---

src/_csrc/blf.c
src/_csrc/blf.h

Niels gave his explicit permission to drop clause 3, the "advertising" clause, from his code. This restores the GPL compatibility of python-bcrypt.

remove advertising clause from niels blowfish code

---

pyproject.toml

It fails with Pip's buggy build env isolation combined with the default fallback for the build backend which is ``setuptools.build_meta.__legacy__``.

Pin the lower bound of PEP517-required setuptools

---

.github/workflows/wheel-builder.yml

Updated the pip version to 18.0.0 instead of 10.0.1 for aarch64.
Resolves problem mentioned in https://github.com/pyca/bcrypt/pull/209#issuecomment-668175031 
@reaperhulk Please review and let me know if any changes required.

Fix for using pip for aarch64

---

.travis.yml
MANIFEST.in
README.rst
mypy.ini
setup.py
src/bcrypt/__init__.py
tox.ini

Setup `py.typed` file in accordance with https://www.python.org/dev/peps/pep-0561/#packaging-type-information and add type hints to api functions.
Internally these functions call out the c extension which is typed as `Any`. For consumers of this project they will have fully typed function signatures.
fixes https://github.com/pyca/bcrypt/issues/215

add: type hints to top level functions

---

setup.py
src/bcrypt/__init__.py
tests/test_bcrypt.py

Since python 2 support is dropped, six dependency can be dropped as well.
`text_type` is `str` in Python 3: https://github.com/benjaminp/six/blob/c0be8815d13df45b6ae471c4c436cce8c192245d/six.py#L44
I also modified exception message slightly, this might be a breaking change. Please tell me if I should change it back.

Drop six dependency

---

.github/workflows/wheel-builder.yml

debian/ubuntu use 4k pages while centos uses 64k pages. 64k pages work
on 4k page systems while a 4k compiled binary will throw this error:
ELF load command alignment not page-aligned
This patch attempts to pass a linker flag that should force 64k page
alignment at all times
Sample run: https://github.com/pyca/bcrypt/runs/993847721?check_suite_focus=true

fix page size on aarch64

---

README.rst
src/_csrc/portable_endian.h
src/_csrc/pycabcrypt.h

These changes allow z/OS users to install bcrypt.
It originally fell into an error statement saying “platform not supported”.
Defining needed macros and types resolves the errors. 
All tests passed.

Installing bcrypt on z/OS

---

.github/workflows/wheel-builder.yml

Reverts pyca/bcrypt#256
We can't bump the `upload-artifact` version used in manylinux wheels because of libc shenangins.

Revert "Bump actions/upload-artifact from 1 to 2.2.3"

---

.github/workflows/wheel-builder.yml

Python-six has been removed from the dependencies with https://github.com/pyca/bcrypt/pull/225. So I guess it's not needed by the worker too.
*I did not check if the patch works**because I don't think I can run it.

python-six uneeded to build wheels

---

setup.py

This typo was introduced in:
* https://github.com/pyca/bcrypt/pull/395/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R17
* https://github.com/pyca/bcrypt/commit/eceb9797#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R17
It seems to have been copied from
https://github.com/pyca/cryptography/commit/ab537a61#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R20

Replace the `cryptography` mention in `setup.py`

---

.github/workflows/ci.yml
setup.cfg

To match https://github.com/pyca/cryptography (re: https://github.com/pyca/cryptography/pull/9506), I only added 3.12 to the test matrix for Ubuntu.
(I did check the tests for macOS and Windows with 3.12, and they all pass :tada:, but it's not included here: https://github.com/hugovk/bcrypt/actions/runs/6130920348/job/16640467738)

Add support for Python 3.12

---

.github/workflows/wheel-builder.yml

Fixed wheels for older versions of macOS

---

README.rst

The code *technically* is in `console`, not `bash`

Correctly use `console` language fence

---

.github/workflows/pypi-publish.yml
.github/workflows/wheel-builder.yml
README.rst
pyproject.toml
src/_bcrypt/src/lib.rs

Backports fixes to pypi-publish from cryptography.
refs #913

Bump version for 4.2.1

---

.github/workflows/ci.yml
.github/workflows/wheel-builder.yml
README.rst
pyproject.toml

per https://github.com/pyca/bcrypt/pull/925#issuecomment-2498951144
Reading over https://github.com/pyca/bcrypt/issues/694 I *think* just moving the cp37m wheel builds to be cp38 is sufficient and bcrypt does still need two wheel builds to work around the ceph/subinterpreter issue.

drop Python 3.7 support

---

.github/workflows/ci.yml
README.rst
src/_bcrypt/src/lib.rs
tests/test_bcrypt.py
tox.ini

Towards fixing #913.
* Adds [pytest-run-parallel](https://github.com/Quansight-Labs/pytest-run-parallel) as a test dependency. This does a good job of detecting thread-unsafe use of global state but doesn't catch thread safety issues due to sharing mutable state stored in objects. I marked one test as thread-unsafe because it uses the `warnings` module, which isn't thread-safe.
* Declares that the rust PyO3 module exprted in `_bcrypt` doesn't use the GIL. It looks like the rust code exports python functions and doesn't define any objects with state. Am I missing something?
* Sets up free-threaded CI using [quansight-labs/setup-python](https://github.com/Quansight-Labs/setup-python).
It looks like the existing tests don't use `threading` at all. Should I add some multithreaded tests? Or is …

Support free-threaded Python 3.13

---

.github/workflows/ci.yml

This is an attempt to unblock CI. The Linux CI already includes this in the cache key.
See https://github.com/pyca/bcrypt/pull/960#issuecomment-2622656272

include matrix.PYTHON.VERSION in CI cache keys

---

.github/workflows/ci.yml
.github/workflows/wheel-builder.yml

The changes in the fork were upstreamed and released in 5.5.0. See https://github.com/actions/setup-python/releases/tag/v5.5.0.

replace quansight-labs/setup-python with actions/setup-python

---

src/_bcrypt/src/lib.rs
tests/test_bcrypt.py

See discussion in #969
Moved some existing test cases (that ensured bytes after the 72th were truncated) to a separate fixture and wrote new tests to assert an exception is raised.
`test_2a_wraparound_bug` is failing with this change, I have to better understand what exactly this is doing and if/how it should be updated.

Raise ValueError if password is longer than 72 bytes
